CC=gcc
OUT_CLIENT=client
OUT_SERVER=server
CLIENT=client.c
SERVER=networking.c
# LIB_MESSAGE=message.c
# OBJ_MESSAGE=message.o

make: $(SERVER)
	# $(CC) -Wall -Wfatal-errors -c $(LIB_MESSAGE)
	# $(CC) -Wall -Wfatal-errors -o $(OUT_CLIENT) $(CLIENT) $(OBJ_MESSAGE)
	$(CC) -Wall -Wfatal-errors -o $(OUT_SERVER) $(SERVER)